version: '3.3'
services:
    webapp:
        restart: unless-stopped
        build: .
        image: timetracker:latest
        env_file:
            - ./.env
        ports:
            - 5555:5555
        volumes:
            - type: bind
              source: /home/splaq/docker/timetrackerapp/uploads
              target: /app/time_tracker/static/uploads

            - type: bind
              source: /home/splaq/docker/timetrackerapp/db
              target: /app/time_tracker/db

networks:
    default:
        external:
            name: nginx-proxy-manager_default