version: '3.9'
services:
    api:
        build: .
        image: timetracker:latest
        ports:
            - 5555:5555
        volumes:
            - type: bind
              source: ./time_tracker/static/uploads
              target: /home/splaq/docker/timetrackerapp

networks:
    default:
        external:
            name: nginx-proxy-manager_default